name: dinewell
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+2

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  get: ^4.6.6
  flutter_otp_text_field: ^1.1.3+2
  flutter_slider_drawer: ^2.1.3 # 15 months
  flutter_slidable: ^3.1.0
  flutter_native_splash: ^2.4.0
  dio: ^5.4.3+1
  connectivity_plus: ^6.0.3
  #internet_connection_checker: ^1.0.0+1 # 19 months
  internet_connection_checker_plus: ^2.4.1
  shared_preferences: ^2.2.3
  fluttertoast: ^8.2.5
  carousel_slider: ^4.2.1  # 17 months
  intl: ^0.19.0
  image_picker: ^1.1.1
  cached_network_image: ^3.3.1
  flutter_rating_bar: ^4.0.1 # 24 months
  url_launcher: ^6.2.6
  qr_flutter: ^4.1.0 # 11 months
  firebase_core: ^2.32.0
  firebase_auth: ^4.20.0
  firebase_analytics: ^10.10.7
  firebase_messaging: ^14.9.4
  flutter_local_notifications: ^17.1.2
  google_places_flutter: ^2.0.8
  geolocator: ^12.0.0
  permission_handler: ^11.3.1
  pinput: ^4.0.0
  path_provider: ^2.1.3
  image_cropper: ^7.1.0
  http: ^1.2.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1 # 12 months

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo2.png"

flutter_native_splash:
  color: "#00BAFF"
  image: assets/icon/icon.png
  color_dark: "#00BAFF"
  image_dark:  assets/icon/icon.png


  ##color: "#2ECC71"
  ##image: assets/icon/icon.png
  ##color_dark: "#2ECC71"
  ##image_dark:  assets/icon/icon.png

  web: false
  android: true
  ios: true
  fullscreen: true

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icon/

  fonts:
    - family: Constantia
      fonts:
        - asset: assets/font/Constantia.ttf

