// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBc06Z6BjBQc0m_tIL2Jt574aEwn-8avro',
    appId: '1:714092055764:web:5f80f443a339ae21aeff41',
    messagingSenderId: '714092055764',
    projectId: 'dinewell-2f574',
    authDomain: 'dinewell-2f574.firebaseapp.com',
    storageBucket: 'dinewell-2f574.appspot.com',
    measurementId: 'G-M94BVQTQQ5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPXMmQx7ublnJKMLwAznjvBedFFKyoBmU',
    appId: '1:714092055764:android:725a72e1283ce30faeff41',
    messagingSenderId: '714092055764',
    projectId: 'dinewell-2f574',
    storageBucket: 'dinewell-2f574.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnPcR5K3Lpw85Fjr3w95tZogt16Zkiqc8',
    appId: '1:714092055764:ios:4b2e0c37f329e2c1aeff41',
    messagingSenderId: '714092055764',
    projectId: 'dinewell-2f574',
    storageBucket: 'dinewell-2f574.appspot.com',
    iosBundleId: 'ca.dinewell',
  );

}