import 'package:dinewell/Constance/appfont.dart';
import 'package:dinewell/Constance/colors.dart';

var primaryColorString = AppColors.primaryColor;
// var primaryColorOldString = '#2ECC71';
var secondaryColorString = AppColors.secondary;

var primaryFont = AppFonts.constaniaFont;

class ConstanceData {
  /*"https://dinewell.itdemo.website/api/en-us/v1"
  "https://testdinewell.truedemo.online/api/en-us/v1"*/
  static String baseUrl = "https://dinewell.winmotto.com";
      //"http://dinewell.winmotto.com";
  static String apiBaseUrl = "$baseUrl/api/en-us/v1";

  static String googleMapKey = "AIzaSyD5tgnRuzYa5BABby4K6nProA_JXHy3VLM";
  static String bseImageUrl = 'assets/images/';

  static String appIconRed = "assets/icon/icon.png";

  static String appIcon = "assets/images/redlogo.png";

  static String logo1 = "${bseImageUrl}logo1.png";
  static String logo2 = "${bseImageUrl}logo2.png";
  static String logo3 = "${bseImageUrl}logo3.png";
  static String logo4 = "${bseImageUrl}logo4.png";

  static String ob1 = "${bseImageUrl}ob1.png";
  static String ob2 = "${bseImageUrl}ob2.png";
  static String ob3 = "${bseImageUrl}ob3.png";
  static String ob4 = "${bseImageUrl}ob4.png";
  static String ob5 = "${bseImageUrl}ob5.png";
  static String ob6 = "${bseImageUrl}ob6.png";

  static String s1 = "${bseImageUrl}s1.png";
  static String s2 = "${bseImageUrl}s2.png";
  static String s3 = "${bseImageUrl}s3.png";
  static String s4 = "${bseImageUrl}s4.png";
  static String s5 = "${bseImageUrl}s5.png";
  static String s6 = "${bseImageUrl}s6.png";
  static String s7 = "${bseImageUrl}s7.png";
  static String s8 = "${bseImageUrl}s8.png";
  static String s9 = "${bseImageUrl}s9.png";
  static String s10 = "${bseImageUrl}s10.png";
  static String s11 = "${bseImageUrl}s11.png";
  static String s12 = "${bseImageUrl}s12.png";
  static String s13 = "${bseImageUrl}s13.png";
  static String s14 = "${bseImageUrl}s14.png";
  static String s15 = "${bseImageUrl}s15.png";
  static String s16 = "${bseImageUrl}s16.png";
  static String s17 = "${bseImageUrl}s17.png";
  static String s18 = "${bseImageUrl}s18.png";
  static String s19 = "${bseImageUrl}s19.png";
  static String s20 = "${bseImageUrl}s20.png";
  static String s21 = "${bseImageUrl}s21.png";
  static String s22 = "${bseImageUrl}s22.png";
  static String s23 = "${bseImageUrl}s23.png";
  static String s24 = "${bseImageUrl}s24.png";
  static String s25 = "${bseImageUrl}s25.png";
  static String s26 = "${bseImageUrl}s26.png";
  static String s27 = "${bseImageUrl}s27.png";
  static String s28 = "${bseImageUrl}s28.png";
  static String s29 = "${bseImageUrl}s29-1.png";
  static String s30 = "${bseImageUrl}s30.png";
  static String s31 = "${bseImageUrl}s31.png";
  static String s32 = "${bseImageUrl}s32.png";
  static String s33 = "${bseImageUrl}s33.png";
  static String s34 = "${bseImageUrl}s34.png";
  static String s35 = "${bseImageUrl}s35.png";
  static String s36 = "${bseImageUrl}s36.png";
  static String s37 = "${bseImageUrl}s37.png";
  static String s38 = "${bseImageUrl}s38.png";
  static String s39 = "${bseImageUrl}s39.jpg";

  static String h1 = "${bseImageUrl}h1.png";
  static String h2 = "${bseImageUrl}h2.png";
  static String h3 = "${bseImageUrl}h3.png";
  static String h4 = "${bseImageUrl}h4.png";
  static String h5 = "${bseImageUrl}h5.png";
  static String h6 = "${bseImageUrl}h6.png";
  static String h7 = "${bseImageUrl}h7.png";
  static String h8 = "${bseImageUrl}h8.png";
  static String h9 = "${bseImageUrl}h9.png";
  static String h10 = "${bseImageUrl}h10.png";
  static String h11 = "${bseImageUrl}h11.png";
  static String h12 = "${bseImageUrl}h12.png";
  static String h13 = "${bseImageUrl}h13.png";
  static String h14 = "${bseImageUrl}h14.png";
  static String h15 = "${bseImageUrl}h15.png";
  static String h17 = "${bseImageUrl}h17.png";
  static String h18 = "${bseImageUrl}h18.png";
  static String h19 = "${bseImageUrl}h19.png";
  static String h20 = "${bseImageUrl}h20.png";
  static String h21 = "${bseImageUrl}h21.png";
  static String h22 = "${bseImageUrl}h22.png";
  static String h23 = "${bseImageUrl}h23.png";
  static String h24 = "${bseImageUrl}h24.png";
  static String h25 = "${bseImageUrl}h25.png";
  static String h26 = "${bseImageUrl}h26.png";
  static String h27 = "${bseImageUrl}h27.png";
  static String h28 = "${bseImageUrl}h28.png";
  static String h29 = "${bseImageUrl}h29.png";
  static String h30 = "${bseImageUrl}h30.png";
  static String h31 = "${bseImageUrl}h31.png";
  static String h32 = "${bseImageUrl}h32.png";
  static String h33 = "${bseImageUrl}h33.png";
  static String h34 = "${bseImageUrl}h34.png";
  static String h35 = "${bseImageUrl}h35.png";
  static String h36 = "${bseImageUrl}h36.png";
  static String h37 = "${bseImageUrl}h37.png";
  static String h38 = "${bseImageUrl}h38.png";
  static String h39 = "${bseImageUrl}h39.png";
  static String h40 = "${bseImageUrl}h40.png";
  static String h41 = "${bseImageUrl}h41.png";
  static String h42 = "${bseImageUrl}h42.png";
  static String h43 = "${bseImageUrl}h43.png";
  static String h44 = "${bseImageUrl}h44.png";
  static String h45 = "${bseImageUrl}h45.png";
  static String h46 = "${bseImageUrl}h46.png";
  static String h47 = "${bseImageUrl}h47.png";
  static String h48 = "${bseImageUrl}h48.png";
  static String h49 = "${bseImageUrl}h49.png";
  static String h50 = "${bseImageUrl}h50.png";
  static String h51 = "${bseImageUrl}h51.png";
  static String h52 = "${bseImageUrl}h52.png";
  static String h53 = "${bseImageUrl}h53.png";

  static String r1 = "${bseImageUrl}r1.png";
  static String r2 = "${bseImageUrl}r2.png";
  static String r3 = "${bseImageUrl}r3.png";
  static String r4 = "${bseImageUrl}r4.png";
  static String r5 = "${bseImageUrl}r5.png";
  static String r6 = "${bseImageUrl}r6.png";
  static String r7 = "${bseImageUrl}r7.png";
  static String r8 = "${bseImageUrl}r8.png";
  static String r9 = "${bseImageUrl}r9.png";
  static String r10 = "${bseImageUrl}r10.png";
  static String r11 = "${bseImageUrl}r11.png";
  static String r12 = "${bseImageUrl}r12.png";
  static String r13 = "${bseImageUrl}r13.png";
  static String r14 = "${bseImageUrl}r14.png";
  static String r15 = "${bseImageUrl}r15.png";
  static String r16 = "${bseImageUrl}r16.png";
  static String r17 = "${bseImageUrl}r17.png";
  static String r18 = "${bseImageUrl}r18.png";
  static String r19 = "${bseImageUrl}r19.png";
  static String r20 = "${bseImageUrl}r20.png";
  static String r21 = "${bseImageUrl}r21.png";
  static String r22 = "${bseImageUrl}r22.png";
  static String r23 = "${bseImageUrl}r23.png";
  static String r24 = "${bseImageUrl}r24.png";
  static String r25 = "${bseImageUrl}r25.png";
  static String r26 = "${bseImageUrl}r26.png";
  static String r27 = "${bseImageUrl}r27.png";
  static String r28 = "${bseImageUrl}r28.png";
  static String r29 = "${bseImageUrl}r29.png";
  static String r30 = "${bseImageUrl}r30.png";
  static String r31 = "${bseImageUrl}r31.png";
  static String r32 = "${bseImageUrl}r32.png";
  static String r33 = "${bseImageUrl}r33.png";
  static String r34 = "${bseImageUrl}r34.png";
  static String r35 = "${bseImageUrl}r35.png";
  static String r36 = "${bseImageUrl}r36.png";
  static String r37 = "${bseImageUrl}r37.png";
  static String r38 = "${bseImageUrl}r38.png";
  static String r39 = "${bseImageUrl}r39.png";
  static String r40 = "${bseImageUrl}r40.png";
  static String r41 = "${bseImageUrl}r41.png";
  static String r42 = "${bseImageUrl}r42.png";
  static String r43 = "${bseImageUrl}r43.png";
  static String r44 = "${bseImageUrl}r44.png";
  static String r45 = "${bseImageUrl}r45.png";
  static String r46 = "${bseImageUrl}r46.png";
  static String r47 = "${bseImageUrl}r47.png";
  static String r48 = "${bseImageUrl}r48.png";
  static String r49 = "${bseImageUrl}r49.png";
  static String r50 = "${bseImageUrl}r50.png";
  static String r51 = "${bseImageUrl}r51.png";
  static String r52 = "${bseImageUrl}r52.png";

  static String k1 = "${bseImageUrl}k1.png";
  static String k2 = "${bseImageUrl}k2.png";
  static String k3 = "${bseImageUrl}k3.png";
  static String k4 = "${bseImageUrl}k4.png";
  static String k5 = "${bseImageUrl}k5.png";
  static String k6 = "${bseImageUrl}k6.png";
  static String k7 = "${bseImageUrl}k7.png";
  static String k8 = "${bseImageUrl}k8.png";
  static String k9 = "${bseImageUrl}k9.png";

  static String authenticated = "authenticated";
  static String userAuthToken = "auth_token";
  static String usersDetails = "user_details";
  static String fcmToken = "fcmToken";
}
